artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts\data_ingestion
  source_url: C:\Users\Cynthia\Downloads\chicken-fecal-image.zip
  local_data_file: C:\Users\Cynthia\Downloads\chicken-fecal-image.zip
  unzip_dir: artifacts\data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updates.h5

  